# Site Settings
title: Joshua Bloom | My House on the Internet
email: joshbloom@gmail.com
description: General background, pictures, etc
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
google_analytics: "UA-78470181-1"

# User Settings
username: Joshua Bloom's Portfolio Selections
user_description: Some text about you.
disqus_username: disqus_username

# Social Media
# Remove the item if you don't need it
github_username: code128
twitter_username: joshbloom
linkedin_username: joshuabloom
instagram_username: joshbloom

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
gems:
  - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Professional Portfolio
    url: /
  - title: About
    url: /about/
  - title: Contact
    url: /contact/
  - title: Presentations
    url: /presentations/    
  - title: Things I make for fun
    url: /ephemera/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
