# Site settings
email: joshbloom@gmail.com
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: UA-78470181-1

# SEO settings
title: Joshua Bloom
description: UX Director with a heart of gold.
url: "http://bloomjosh.com"
twitter_username: joshbloom
default_img: /img/josh_bg_sm.jpg

# Profile settings
name: Joshua Bloom
profile_img: /img/josh_bg.jpg
profile: UX Director with a heart of gold. Enjoys creation in all of it's forms. If you're looking to bribe him with something that fits in a bag, think <strong>scotch</strong> or <strong>rare hand tools</strong>. If you want to ensure success go with one of <strong><a style="text-decoration:underline;" href="http://www.cycleworld.com/2017-bmw-r1200gs-rallye-exclusive-first-look-review-eicma">these</a></strong>.
social:
  github: https://github.com/code128/
  linkedin: https://www.linkedin.com/in/jbloom
  instagram: https://www.instagram.com/joshbloom/
  twitter: https://twitter.com/joshbloom
  

# Build settings
exclude: ["_data", _resources", "deploy.sh", "Gemfile", "Gemfile.lock", "LICENSE.txt", "README.md"]
markdown: kramdown
permalink: /:year/:month/:day/:title/


# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
